import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "../styles/globals.css";
import "@radix-ui/themes/styles.css";
import UserProvider from "@/providers/UserProvider";
import localFont from 'next/font/local'
import SideBarProvider from "@/providers/SideBarProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// import '../../public/fonts/DIN Round Pro/dinroundpro.otf'
const dinround = localFont({
  src: [
    {
      path: '../../public/fonts/DIN Round Pro/dinroundpro_light.otf',
      weight: '100'
    },
    {
      path: '../../public/fonts/DIN Round Pro/dinroundpro.otf',
      weight: '400'
    },
    {
      path: '../../public/fonts/DIN Round Pro/dinroundpro_medi.otf',
      weight: '500'
    },
    {
      path: '../../public/fonts/DIN Round Pro/dinroundpro_bold.otf',
      weight: '600'
    },
    {
      path: '../../public/fonts/DIN Round Pro/dinroundpro_black.otf',
      weight: '700'
    },


  ],
  variable: '--font-dinround'
})

export const metadata: Metadata = {
  title: "Learn Korean",
  description: "Generated by create next app",
  icons: {
    icon: '/LE_SSERAFIM_logo.svg',
  },
};

console.log(dinround)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <SideBarProvider>
        <UserProvider>
          <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${dinround.variable} font-(family-name:--font-dinround) antialiased `}>
              {children}
            </body>
          </html>
        </UserProvider>
      </SideBarProvider>

    </ClerkProvider>
  );
}
